services:
  sender:
    build:
      context: ./sender
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - ./sender:/sender
      - ./sessions:/sessions
      - ./receiver/media:/media:ro
    tty: true
    restart: unless-stopped

  receiver:
    build:
      context: ./receiver
    command: sh -c "python3 main.py & python3 media_server.py"
    ports:
      - 8181:8181
    env_file:
      - .env
    volumes:
      - ./sessions:/sessions
      - ./receiver/media:/receiver/media
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - sender
