version: '3.8'

services:
    sender:
        command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
        build:
            context: ./sender
            dockerfile: Dockerfile
        env_file:
          - .env
        ports:
          - 8001:8000
        volumes:
          - ./sender:/sender
          - ./sessions:/sessions
          - ./userbot_media:/media:ro
        tty: true
    receiver:
        command: sh -c "python3 main.py & python3 media_server.py"
        build:
            context: .
            dockerfile: receiver/Dockerfile
        env_file:
          - .env
        volumes:
          - ./sessions:/sessions
          - ./userbot_media:/receiver/media
        ports:
          - 8181:8181
        tty: true
        stdin_open: true
