services:
  sender:
    build:
      context: ./sender
    ports:
      - "8001:8001"
    restart: unless-stopped
  receiver:
    build:
      context: ./receiver
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - sender
